let
    Source = cw_rest.Contents(),
    #"service/tickets?fields=id,summary,recordType,board,status,company,resources,siteName,city,stateIdentifier,contact,type,subType,priority,source,actualHours,closedDate,closedBy,closedFlag,respondMinutes,_info&conditions=board/name='End-User Requests'and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Alerts and Maintenance' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='AutoElevate'and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Backups' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Grayco User Requests' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Security' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='To Do' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Labtech - Alert Cleared' and _info/dateEntered>[2020-01-01T18:04:26Z]&pageSize=1000" = Source{[Name="service/tickets?fields=id,summary,recordType,board,status,company,siteName,city,stateIdentifier,contact,type,subType,priority,source,actualHours,closedDate,closedBy,closedFlag,respondMinutes,_info&conditions=board/name='End-User Requests' and _info/dateEntered>[2020-01-01T18:04:26Z]&pageSize=1000"]}[Data],
    #"Expanded board" = Table.ExpandRecordColumn(#"service/tickets?fields=id,summary,recordType,board,status,company,resources,siteName,city,stateIdentifier,contact,type,subType,priority,source,actualHours,closedDate,closedBy,closedFlag,respondMinutes,_info&conditions=board/name='End-User Requests'and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Alerts and Maintenance' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='AutoElevate'and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Backups' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Grayco User Requests' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Security' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='To Do' and _info/dateEntered>[2020-01-01T18:04:26Z] OR board/name='Labtech - Alert Cleared' and _info/dateEntered>[2020-01-01T18:04:26Z]&pageSize=1000", "board", {"name"}, {"board.name"}),
    #"Expanded status" = Table.ExpandRecordColumn(#"Expanded board", "status", {"name"}, {"status.name"}),
    #"Expanded _info" = Table.ExpandRecordColumn(#"Expanded status", "_info", {"lastUpdated", "updatedBy", "dateEntered", "enteredBy"}, {"_info.lastUpdated", "_info.updatedBy", "_info.dateEntered", "_info.enteredBy"}),
    #"Expanded source" = Table.ExpandRecordColumn(#"Expanded _info", "source", {"name"}, {"source.name"}),
    #"Expanded priority" = Table.ExpandRecordColumn(#"Expanded source", "priority", {"name"}, {"priority.name"}),
    #"Expanded contact" = Table.ExpandRecordColumn(#"Expanded priority", "contact", {"id", "name", "_info"}, {"contact.id", "contact.name", "contact._info"}),
    #"Expanded company" = Table.ExpandRecordColumn(#"Expanded contact", "company", {"id", "identifier", "name", "_info"}, {"company.id", "company.identifier", "company.name", "company._info"}),
    #"Expanded type" = Table.ExpandRecordColumn(#"Expanded company", "type", {"id", "name", "_info"}, {"type.id", "type.name", "type._info"}),
    #"Expanded subType" = Table.ExpandRecordColumn(#"Expanded type", "subType", {"id", "name", "_info"}, {"subType.id", "subType.name", "subType._info"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded subType",{{"_info.dateEntered", type datetime}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "_info.dateEntered", "_info.dateEntered - Copy"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"_info.dateEntered - Copy", type date}})
in
    #"Changed Type1"
